### ISSUE TITLE
Lightweight Documentation

### ISSUE THREAD

**Issue by KouroshSimpkins** [KouroshSimpkins/Constituency-Mapper#5]
### We Need Documentation!

Would like something a bit more detailed for the README.md, that can outline some key functionality within the code, as well as explaining what the key final outcome is. Improving the documentation will help when bringing new team-members on board, especially as I am not able to attend every single CampaignLab event in person anymore. 

It would also be useful to explain how the development environment is set up, in fact I believe that is of the highest importance, to ensure that all developers are working with a database that is always the same shape. For this, there is a function called [generate_constituency_database](https://github.com/KouroshSimpkins/Constituency-Mapper/blob/7c6a02dbb6e7f9572554f4d0b7c0163c6737db09/dbInteraction.py#L52) which builds the database, as long as a mysql server is detected on localhost.

**Comment by riku-mito** [comment]
Hello, I’m interested in contributing to this. May I please get assigned to this issue?

**Comment by KouroshSimpkins** [comment]
I've assigned it to you, if you have any questions about anything please feel free to reach out!

**Comment by riku-mito** [comment]
Thank you very much!

**Comment by KouroshSimpkins** [comment]
Finished by #6
